In [24]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cpu


## Intoduction to Tensors


### Creating tensors

In [25]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [26]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [27]:
scalar.ndim


0

In [28]:
#get tensor back as python int
scalar.item()

7

In [29]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [30]:
vector.ndim


1

In [31]:
vector.shape


torch.Size([2])

In [32]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [33]:
MATRIX.ndim


2

In [34]:
MATRIX.shape


torch.Size([2, 2])

In [35]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [36]:
TENSOR.ndim

3

In [37]:
TENSOR.shape

torch.Size([2, 3, 3])

In [38]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [39]:
TENSOR[0][0]

tensor([1, 2, 3])

In [40]:
TENSOR[0][0][0]

tensor(1)

###