In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cpu


## Intoduction to Tensors


### Creating tensors

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [7]:
vector.ndim


1

In [8]:
vector.shape


torch.Size([2])

In [9]:
#matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim


2

In [11]:
matrix.shape


torch.Size([2, 2])

In [18]:
Tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
Tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [19]:
Tensor.ndim

3

In [20]:
Tensor.shape

torch.Size([2, 3, 3])

In [21]:
Tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
Tensor[0][0]

tensor([1, 2, 3])

In [23]:
Tensor[0][0][0]

tensor(1)