In [80]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cu118


## Intoduction to Tensors

### Creating tensors

In [81]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [82]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [83]:
scalar.ndim


0

In [84]:
#get tensor back as python int
scalar.item()

7

In [85]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [86]:
vector.ndim


1

In [87]:
vector.shape


torch.Size([2])

In [88]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [89]:
MATRIX.ndim


2

In [90]:
MATRIX.shape


torch.Size([2, 2])

In [91]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [92]:
TENSOR.ndim

3

In [93]:
TENSOR.shape

torch.Size([2, 3, 3])

In [94]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [95]:
TENSOR[0][0]

tensor([1, 2, 3])

In [96]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [97]:
#creating a random tensors
random_tensor=torch.rand(2,3,3)
random_tensor

tensor([[[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739],
         [0.2666, 0.6274, 0.2696]],

        [[0.4414, 0.2969, 0.8317],
         [0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062]]])

In [98]:
random_tensor.ndim

3

In [99]:
#creating a random tensor with similar shape to a image tensor
random_image_tensor=torch.rand(size=(3,244,224))#colour channel, height and width 
random_image_tensor

tensor([[[0.9516, 0.0753, 0.8860,  ..., 0.1332, 0.4118, 0.2576],
         [0.3470, 0.0240, 0.7797,  ..., 0.7498, 0.2409, 0.1626],
         [0.3403, 0.6049, 0.7574,  ..., 0.9597, 0.8029, 0.2662],
         ...,
         [0.9581, 0.3374, 0.5838,  ..., 0.6053, 0.4600, 0.2569],
         [0.6966, 0.7573, 0.0894,  ..., 0.5751, 0.6938, 0.7547],
         [0.7779, 0.0320, 0.5874,  ..., 0.7081, 0.6833, 0.4138]],

        [[0.8463, 0.2374, 0.0065,  ..., 0.1270, 0.2590, 0.3408],
         [0.9384, 0.7282, 0.0803,  ..., 0.4074, 0.7965, 0.6587],
         [0.3127, 0.4278, 0.5464,  ..., 0.7450, 0.3476, 0.5245],
         ...,
         [0.9072, 0.9405, 0.7242,  ..., 0.7469, 0.5791, 0.6606],
         [0.1196, 0.4621, 0.5850,  ..., 0.4959, 0.9773, 0.2584],
         [0.6194, 0.7278, 0.1385,  ..., 0.9007, 0.5399, 0.7978]],

        [[0.4431, 0.7507, 0.1253,  ..., 0.5450, 0.4651, 0.0590],
         [0.9339, 0.5573, 0.8824,  ..., 0.1711, 0.6248, 0.6398],
         [0.9061, 0.1220, 0.0480,  ..., 0.7191, 0.5014, 0.

In [100]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 224]), 3)

### Zeros and Ones

In [101]:
#creating all zeros
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [102]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [103]:
#creating all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [104]:
ones.dtype

torch.float32

### Creating tensors with a range

In [105]:
one_to_hundred=torch.arange(start=0,end=100,step=9)
one_to_hundred

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [106]:
#creating a tensor like
hundred_zeros=torch.zeros_like(input=one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [107]:
#lfoat 32
float_32_tensor=torch.tensor([3.0,6.0,9.0], 
                             dtype=None, # specify dtype of tensor, if None, it will be inferred from data
                             device=None, # specify device of tensor, if None, it will be inferred from data
                             requires_grad=False # specify if tensor requires gradient, default is False
                             )
float_32_tensor, float_32_tensor.dtype


(tensor([3., 6., 9.]), torch.float32)

In [108]:
floar_16_tensor=float_32_tensor.type(torch.float16)
floar_16_tensor, floar_16_tensor.dtype


(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [109]:
float_32_tensor*floar_16_tensor,(float_32_tensor*floar_16_tensor).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [110]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([3, 6, 9], dtype=torch.int32), torch.int32)

In [111]:
int_32_tensor*floar_16_tensor,(int_32_tensor*floar_16_tensor).dtype

(tensor([ 9., 36., 81.], dtype=torch.float16), torch.float16)

### Getting info from Tensors
info like: datatype, shape of tensor and device its present

In [112]:
#creating a general tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.3214, 0.7572, 0.2080, 0.1460],
        [0.6122, 0.0052, 0.8830, 0.2791],
        [0.4999, 0.1466, 0.1136, 0.2463]])

In [113]:
print('Datatype of Tensor: ',some_tensor.dtype)
print('Shape of Tensor: ',some_tensor.shape)
print('Device of Tensor: ',some_tensor.device)

Datatype of Tensor:  torch.float32
Shape of Tensor:  torch.Size([3, 4])
Device of Tensor:  cpu


### Manipulating a tensor

In [114]:
#creating a dummy tensor
dummy_tensor=torch.tensor([1,2,3])
dummy_tensor+100

tensor([101, 102, 103])

In [115]:
dummy_tensor*100

tensor([100, 200, 300])

In [116]:
dummy_tensor-100

tensor([-99, -98, -97])

In [117]:
torch.mul(dummy_tensor,10)

tensor([10, 20, 30])

In [118]:
torch.add(dummy_tensor,10)

tensor([11, 12, 13])

### Matrix mulltiplication

In [119]:
test_tensor=torch.tensor([1,2,3])
second_tensor=torch.tensor([10,20,30])
test_tensor, second_tensor

(tensor([1, 2, 3]), tensor([10, 20, 30]))

In [120]:
%%time
test_tensor*second_tensor

CPU times: total: 0 ns
Wall time: 74.4 μs


tensor([10, 40, 90])

In [121]:
%%time
torch.matmul(test_tensor,second_tensor)

CPU times: total: 0 ns
Wall time: 277 μs


tensor(140)

In [122]:
#matrix multiplication by hand
1*10+2*20+3*30

140

In [123]:
%%time
val=0
for i in range(len(test_tensor)):
    val+=test_tensor[i]*second_tensor[i]
print(val)

tensor(140)
CPU times: total: 0 ns
Wall time: 1.21 ms


### Finding min, max, mean ,sum , etc (tensor aggregation)

In [124]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [125]:
torch.min(x),torch.max(x),torch.sum(x)

(tensor(0), tensor(90), tensor(450))

In [126]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean() # mean requires float tensor

(tensor(45.), tensor(45.))

In [127]:
#finding positional max and min
x.argmax(),x.argmin()

(tensor(9), tensor(0))

### Reshaping, Stacking, Sqeezing and Unsqueeezing tensors

In [128]:
x=torch.arange(1.,10.)
x,x.dtype,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32, torch.Size([9]))

In [129]:
x_reshaped=x.reshape(1,3,3)
x_reshaped,x_reshaped.dtype,x_reshaped.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32,
 torch.Size([1, 3, 3]))

In [130]:
z=x.view(3,3)
z,z.dtype,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32,
 torch.Size([3, 3]))

In [131]:
print(f"original x: {x}, z: {z}")
z[:,0]=9
print(f"After changeing z x: {x}, z: {z}")

original x: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), z: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
After changeing z x: tensor([9., 2., 3., 9., 5., 6., 9., 8., 9.]), z: tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]])


In [132]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked,x_stacked.dtype,x_stacked.shape

(tensor([[9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.]]),
 torch.float32,
 torch.Size([4, 9]))

In [133]:
print(x_reshaped,x_reshaped.dtype,x_reshaped.shape)
x_squeezed=x_reshaped.squeeze()
print(x_squeezed,x_squeezed.dtype,x_squeezed.shape)

tensor([[[9., 2., 3.],
         [9., 5., 6.],
         [9., 8., 9.]]]) torch.float32 torch.Size([1, 3, 3])
tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]]) torch.float32 torch.Size([3, 3])


In [134]:
print(x_squeezed,x_squeezed.dtype,x_squeezed.shape)
x_unsqueezed=x_squeezed.unsqueeze(dim=2)
print(x_unsqueezed,x_unsqueezed.dtype,x_unsqueezed.shape)

tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]]) torch.float32 torch.Size([3, 3])
tensor([[[9.],
         [2.],
         [3.]],

        [[9.],
         [5.],
         [6.]],

        [[9.],
         [8.],
         [9.]]]) torch.float32 torch.Size([3, 3, 1])


## Indexing (Selecting data from tensors)

In [135]:
x=torch.arange(1.,10.).reshape(1,3,3)
x,x.dtype,x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32,
 torch.Size([1, 3, 3]))

In [136]:
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [137]:
x[0][0]

tensor([1., 2., 3.])

In [138]:
x[0][0][0]

tensor(1.)

In [139]:
x[:,0]

tensor([[1., 2., 3.]])

In [140]:
x[:,:,0]

tensor([[1., 4., 7.]])

In [141]:
x[0,1,:]

tensor([4., 5., 6.])

## Reproducbility(trying to kake random out of random)

In [142]:
import torch

rand_tensor_a=torch.rand(3,4)
rand_tensor_b=torch.rand(3,4)

print(rand_tensor_a, rand_tensor_b,rand_tensor_a==rand_tensor_b)

tensor([[0.8139, 0.8667, 0.9803, 0.2567],
        [0.0408, 0.1031, 0.7575, 0.9418],
        [0.9886, 0.0870, 0.5018, 0.7681]]) tensor([[0.2231, 0.0379, 0.2087, 0.6413],
        [0.6254, 0.1182, 0.0951, 0.0518],
        [0.2511, 0.3214, 0.8627, 0.5522]]) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [143]:
import torch

RANDOM_SEED=42

torch.manual_seed(RANDOM_SEED)  # Set seed for reproducibility

rand_tensor_c=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)  # Set seed for reproducibility

rand_tensor_d=torch.rand(3,4)

print(rand_tensor_c, rand_tensor_d,rand_tensor_c==rand_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs

In [144]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())


2.7.1+cu118
11.8
True


In [145]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")


Using device: cuda


In [146]:
torch.cuda.device_count()

1

## Putting tensors (and Models) on GPU

In [147]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)
tensor_on_gpu=torch.tensor([1,2,3],device=device)
print(tensor_on_gpu,tensor_on_gpu.device)

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0') cuda:0


## Moving tensors back to CPU

In [148]:
tensor_on_gpu.numpy()#can't use numpy on gpu

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [149]:
tensor_backto_cpu=tensor_on_gpu.cpu().numpy()#converting to cpu just before changing to numpy
tensor_backto_cpu

array([1, 2, 3])