In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cpu


## Intoduction to Tensors


### Creating tensors

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim


0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [8]:
vector.ndim


1

In [9]:
vector.shape


torch.Size([2])

In [10]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim


2

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

In [18]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [19]:
#creating a random tensors
random_tensor=torch.rand(2,3,3)
random_tensor

tensor([[[0.7986, 0.4119, 0.6497],
         [0.9865, 0.7404, 0.3460],
         [0.3162, 0.2794, 0.7445]],

        [[0.6923, 0.7579, 0.0228],
         [0.7283, 0.9407, 0.1126],
         [0.9456, 0.1370, 0.9854]]])

In [20]:
random_tensor.ndim

3

In [21]:
#creating a random tensor with similar shape to a image tensor
random_image_tensor=torch.rand(size=(3,244,224))#colour channel, height and width 
random_image_tensor

tensor([[[0.1083, 0.5880, 0.6923,  ..., 0.2782, 0.0817, 0.8202],
         [0.2683, 0.8738, 0.0978,  ..., 0.8898, 0.2841, 0.6468],
         [0.5739, 0.5639, 0.6744,  ..., 0.6114, 0.3844, 0.9142],
         ...,
         [0.8985, 0.7678, 0.0406,  ..., 0.9020, 0.6979, 0.4927],
         [0.1929, 0.9993, 0.2164,  ..., 0.8146, 0.3079, 0.9342],
         [0.1496, 0.2602, 0.9639,  ..., 0.8229, 0.5274, 0.6364]],

        [[0.4085, 0.5302, 0.1055,  ..., 0.0045, 0.0248, 0.3442],
         [0.4154, 0.4127, 0.5947,  ..., 0.9577, 0.5042, 0.3820],
         [0.0796, 0.3786, 0.0093,  ..., 0.5616, 0.9208, 0.2522],
         ...,
         [0.4665, 0.9840, 0.7058,  ..., 0.0020, 0.6595, 0.6313],
         [0.9106, 0.1744, 0.1256,  ..., 0.3580, 0.8451, 0.3620],
         [0.0647, 0.4755, 0.9351,  ..., 0.2357, 0.4426, 0.5822]],

        [[0.9523, 0.0291, 0.3482,  ..., 0.8551, 0.4826, 0.0511],
         [0.9175, 0.9012, 0.7510,  ..., 0.0172, 0.4945, 0.2856],
         [0.4327, 0.8464, 0.1484,  ..., 0.0013, 0.9099, 0.

In [22]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 224]), 3)

### Zeros and Ones

In [23]:
#creating all zeros
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [25]:
#creating all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Creating tensors with a range

In [27]:
one_to_hundred=torch.arange(start=0,end=100,step=9)
one_to_hundred

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [28]:
#creating a tensor like
hundred_zeros=torch.zeros_like(input=one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])