In [24]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cpu


## Intoduction to Tensors


### Creating tensors

In [41]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [42]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [43]:
scalar.ndim


0

In [44]:
#get tensor back as python int
scalar.item()

7

In [45]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [46]:
vector.ndim


1

In [47]:
vector.shape


torch.Size([2])

In [48]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [49]:
MATRIX.ndim


2

In [50]:
MATRIX.shape


torch.Size([2, 2])

In [51]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [52]:
TENSOR.ndim

3

In [53]:
TENSOR.shape

torch.Size([2, 3, 3])

In [54]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
TENSOR[0][0]

tensor([1, 2, 3])

In [56]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [60]:
#creating a random tensors
random_tensor=torch.rand(2,3,3)
random_tensor

tensor([[[0.0937, 0.3030, 0.6819],
         [0.6403, 0.9223, 0.3751],
         [0.5902, 0.3721, 0.4733]],

        [[0.1648, 0.4131, 0.6029],
         [0.4771, 0.0446, 0.6527],
         [0.4122, 0.8250, 0.4627]]])

In [61]:
random_tensor.ndim

3

In [62]:
#creating a random tensor with similar shape to a image tensor
random_image_tensor=torch.rand(size=(244,224,3))
random_image_tensor

tensor([[[0.2071, 0.4430, 0.0293],
         [0.0818, 0.5222, 0.4844],
         [0.3919, 0.7166, 0.7341],
         ...,
         [0.3339, 0.4550, 0.6667],
         [0.1381, 0.7884, 0.2029],
         [0.3773, 0.2485, 0.0816]],

        [[0.6291, 0.6004, 0.8165],
         [0.1484, 0.7378, 0.3850],
         [0.8693, 0.8049, 0.1381],
         ...,
         [0.9540, 0.6945, 0.6758],
         [0.7157, 0.5530, 0.1016],
         [0.4938, 0.7673, 0.1097]],

        [[0.5365, 0.2927, 0.9044],
         [0.6021, 0.5765, 0.9952],
         [0.1655, 0.6369, 0.3182],
         ...,
         [0.0681, 0.0039, 0.6628],
         [0.7785, 0.0074, 0.0725],
         [0.1408, 0.7596, 0.1515]],

        ...,

        [[0.1471, 0.1384, 0.0094],
         [0.7947, 0.3788, 0.7163],
         [0.2308, 0.2246, 0.1195],
         ...,
         [0.8892, 0.6417, 0.7281],
         [0.2032, 0.0520, 0.6875],
         [0.0247, 0.0141, 0.9516]],

        [[0.3540, 0.9278, 0.8382],
         [0.9759, 0.9339, 0.2363],
         [0.