In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cu118


## Intoduction to Tensors

### Creating tensors

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [7]:
vector.ndim


1

In [8]:
vector.shape


torch.Size([2])

In [9]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim


2

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR[0][0]

tensor([1, 2, 3])

In [17]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [18]:
#creating a random tensors
random_tensor=torch.rand(2,3,3)
random_tensor

tensor([[[0.2458, 0.9740, 0.3673],
         [0.8701, 0.8538, 0.0950],
         [0.1347, 0.7540, 0.5904]],

        [[0.6455, 0.1245, 0.3753],
         [0.2759, 0.0946, 0.5029],
         [0.6793, 0.1251, 0.1445]]])

In [19]:
random_tensor.ndim

3

In [20]:
#creating a random tensor with similar shape to a image tensor
random_image_tensor=torch.rand(size=(3,244,224))#colour channel, height and width 
random_image_tensor

tensor([[[2.2182e-02, 4.7994e-01, 6.1517e-01,  ..., 7.3696e-01,
          4.4275e-01, 8.6558e-01],
         [1.9112e-01, 3.0663e-01, 8.8582e-01,  ..., 1.0634e-01,
          5.4454e-01, 2.5833e-04],
         [5.1236e-02, 3.8981e-01, 3.0964e-01,  ..., 1.9573e-01,
          9.4630e-03, 6.5145e-01],
         ...,
         [8.2163e-01, 6.5383e-01, 3.7323e-01,  ..., 8.2573e-01,
          4.2576e-01, 3.5252e-01],
         [9.8836e-03, 5.2862e-01, 2.7760e-01,  ..., 6.2975e-01,
          2.1988e-01, 4.2437e-01],
         [2.1694e-01, 4.8338e-01, 7.3325e-01,  ..., 8.7270e-02,
          3.5674e-01, 8.1385e-01]],

        [[6.5467e-01, 4.2154e-01, 4.4013e-01,  ..., 6.5495e-01,
          5.4832e-01, 7.9087e-01],
         [4.1985e-01, 5.5701e-04, 6.2096e-01,  ..., 1.3518e-01,
          9.4520e-01, 6.8901e-01],
         [4.6868e-01, 5.7688e-01, 6.1190e-01,  ..., 8.3030e-01,
          1.7856e-01, 1.8575e-01],
         ...,
         [2.2490e-01, 6.8446e-01, 1.8197e-01,  ..., 9.5298e-01,
          6.044

In [21]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 224]), 3)

### Zeros and Ones

In [22]:
#creating all zeros
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [24]:
#creating all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating tensors with a range

In [26]:
one_to_hundred=torch.arange(start=0,end=100,step=9)
one_to_hundred

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [27]:
#creating a tensor like
hundred_zeros=torch.zeros_like(input=one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [28]:
#lfoat 32
float_32_tensor=torch.tensor([3.0,6.0,9.0], 
                             dtype=None, # specify dtype of tensor, if None, it will be inferred from data
                             device=None, # specify device of tensor, if None, it will be inferred from data
                             requires_grad=False # specify if tensor requires gradient, default is False
                             )
float_32_tensor, float_32_tensor.dtype


(tensor([3., 6., 9.]), torch.float32)

In [29]:
floar_16_tensor=float_32_tensor.type(torch.float16)
floar_16_tensor, floar_16_tensor.dtype


(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [30]:
float_32_tensor*floar_16_tensor,(float_32_tensor*floar_16_tensor).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [31]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([3, 6, 9], dtype=torch.int32), torch.int32)

In [32]:
int_32_tensor*floar_16_tensor,(int_32_tensor*floar_16_tensor).dtype

(tensor([ 9., 36., 81.], dtype=torch.float16), torch.float16)

### Getting info from Tensors
info like: datatype, shape of tensor and device its present

In [33]:
#creating a general tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8795, 0.9334, 0.1188, 0.1123],
        [0.3698, 0.0738, 0.1289, 0.7790],
        [0.5869, 0.6834, 0.2289, 0.9778]])

In [34]:
print('Datatype of Tensor: ',some_tensor.dtype)
print('Shape of Tensor: ',some_tensor.shape)
print('Device of Tensor: ',some_tensor.device)

Datatype of Tensor:  torch.float32
Shape of Tensor:  torch.Size([3, 4])
Device of Tensor:  cpu


### Manipulating a tensor

In [35]:
#creating a dummy tensor
dummy_tensor=torch.tensor([1,2,3])
dummy_tensor+100

tensor([101, 102, 103])

In [36]:
dummy_tensor*100

tensor([100, 200, 300])

In [37]:
dummy_tensor-100

tensor([-99, -98, -97])

In [38]:
torch.mul(dummy_tensor,10)

tensor([10, 20, 30])

In [39]:
torch.add(dummy_tensor,10)

tensor([11, 12, 13])

### Matrix mulltiplication

In [40]:
test_tensor=torch.tensor([1,2,3])
second_tensor=torch.tensor([10,20,30])
test_tensor, second_tensor

(tensor([1, 2, 3]), tensor([10, 20, 30]))

In [41]:
%%time
test_tensor*second_tensor

CPU times: total: 0 ns
Wall time: 196 μs


tensor([10, 40, 90])

In [42]:
%%time
torch.matmul(test_tensor,second_tensor)

CPU times: total: 0 ns
Wall time: 174 μs


tensor(140)

In [43]:
#matrix multiplication by hand
1*10+2*20+3*30

140

In [44]:
%%time
val=0
for i in range(len(test_tensor)):
    val+=test_tensor[i]*second_tensor[i]
print(val)

tensor(140)
CPU times: total: 0 ns
Wall time: 1.06 ms


### Finding min, max, mean ,sum , etc (tensor aggregation)

In [45]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [46]:
torch.min(x),torch.max(x),torch.sum(x)

(tensor(0), tensor(90), tensor(450))

In [47]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean() # mean requires float tensor

(tensor(45.), tensor(45.))

In [48]:
#finding positional max and min
x.argmax(),x.argmin()

(tensor(9), tensor(0))

### Reshaping, Stacking, Sqeezing and Unsqueeezing tensors

In [49]:
x=torch.arange(1.,10.)
x,x.dtype,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32, torch.Size([9]))

In [50]:
x_reshaped=x.reshape(1,3,3)
x_reshaped,x_reshaped.dtype,x_reshaped.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32,
 torch.Size([1, 3, 3]))

In [51]:
z=x.view(3,3)
z,z.dtype,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32,
 torch.Size([3, 3]))

In [52]:
print(f"original x: {x}, z: {z}")
z[:,0]=9
print(f"After changeing z x: {x}, z: {z}")

original x: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), z: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
After changeing z x: tensor([9., 2., 3., 9., 5., 6., 9., 8., 9.]), z: tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]])


In [53]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked,x_stacked.dtype,x_stacked.shape

(tensor([[9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.]]),
 torch.float32,
 torch.Size([4, 9]))

In [54]:
print(x_reshaped,x_reshaped.dtype,x_reshaped.shape)
x_squeezed=x_reshaped.squeeze()
print(x_squeezed,x_squeezed.dtype,x_squeezed.shape)

tensor([[[9., 2., 3.],
         [9., 5., 6.],
         [9., 8., 9.]]]) torch.float32 torch.Size([1, 3, 3])
tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]]) torch.float32 torch.Size([3, 3])


In [55]:
print(x_squeezed,x_squeezed.dtype,x_squeezed.shape)
x_unsqueezed=x_squeezed.unsqueeze(dim=2)
print(x_unsqueezed,x_unsqueezed.dtype,x_unsqueezed.shape)

tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]]) torch.float32 torch.Size([3, 3])
tensor([[[9.],
         [2.],
         [3.]],

        [[9.],
         [5.],
         [6.]],

        [[9.],
         [8.],
         [9.]]]) torch.float32 torch.Size([3, 3, 1])


## Indexing (Selecting data from tensors)

In [56]:
x=torch.arange(1.,10.).reshape(1,3,3)
x,x.dtype,x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32,
 torch.Size([1, 3, 3]))

In [57]:
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [58]:
x[0][0]

tensor([1., 2., 3.])

In [59]:
x[0][0][0]

tensor(1.)

In [60]:
x[:,0]

tensor([[1., 2., 3.]])

In [61]:
x[:,:,0]

tensor([[1., 4., 7.]])

In [62]:
x[0,1,:]

tensor([4., 5., 6.])

## Reproducbility(trying to kake random out of random)

In [63]:
import torch

rand_tensor_a=torch.rand(3,4)
rand_tensor_b=torch.rand(3,4)

print(rand_tensor_a, rand_tensor_b,rand_tensor_a==rand_tensor_b)

tensor([[0.4037, 0.5179, 0.7651, 0.0457],
        [0.1419, 0.9173, 0.6121, 0.0683],
        [0.8537, 0.2565, 0.0490, 0.8255]]) tensor([[0.2647, 0.1367, 0.5300, 0.6446],
        [0.2601, 0.3410, 0.2700, 0.4760],
        [0.8653, 0.1390, 0.0347, 0.1645]]) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [64]:
import torch

RANDOM_SEED=42

torch.manual_seed(RANDOM_SEED)  # Set seed for reproducibility

rand_tensor_c=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)  # Set seed for reproducibility

rand_tensor_d=torch.rand(3,4)

print(rand_tensor_c, rand_tensor_d,rand_tensor_c==rand_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs

In [65]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())


2.7.1+cu118
11.8
True


In [67]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")


Using device: cuda


In [68]:
torch.cuda.device_count()

1

## Putting tensors (and Models) on GPU

In [73]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)
tensor_on_gpu=torch.tensor([1,2,3],device=device)
print(tensor_on_gpu,tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


## Moving tensors back to CPU

In [75]:
tensor_on_gpu.numpy()#can't use numpy on gpu

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [77]:
tensor_backto_cpu=tensor_on_gpu.cpu().numpy()#converting to cpu just before changing to numpy
tensor_backto_cpu

array([1, 2, 3])