In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cpu


## Intoduction to Tensors


### Creating tensors

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [7]:
vector.ndim


1

In [8]:
vector.shape


torch.Size([2])

In [9]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim


2

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR[0][0]

tensor([1, 2, 3])

In [17]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [18]:
#creating a random tensors
random_tensor=torch.rand(2,3,3)
random_tensor

tensor([[[0.2204, 0.8271, 0.4813],
         [0.2156, 0.1572, 0.1353],
         [0.6926, 0.7856, 0.5433]],

        [[0.0761, 0.0659, 0.5193],
         [0.0465, 0.2903, 0.5615],
         [0.0341, 0.3397, 0.9645]]])

In [19]:
random_tensor.ndim

3

In [20]:
#creating a random tensor with similar shape to a image tensor
random_image_tensor=torch.rand(size=(3,244,224))#colour channel, height and width 
random_image_tensor

tensor([[[0.1097, 0.4485, 0.2775,  ..., 0.0186, 0.3208, 0.1491],
         [0.5230, 0.9888, 0.4031,  ..., 0.7913, 0.9232, 0.1532],
         [0.9632, 0.5056, 0.0927,  ..., 0.1970, 0.2081, 0.4227],
         ...,
         [0.7393, 0.2854, 0.7947,  ..., 0.2229, 0.1038, 0.0775],
         [0.5478, 0.2371, 0.6913,  ..., 0.5779, 0.0510, 0.5379],
         [0.6986, 0.8200, 0.6517,  ..., 0.7395, 0.8167, 0.1361]],

        [[0.0385, 0.5415, 0.9279,  ..., 0.7280, 0.6333, 0.9279],
         [0.4990, 0.4964, 0.1813,  ..., 0.1287, 0.2715, 0.6934],
         [0.2582, 0.9427, 0.2023,  ..., 0.4638, 0.1049, 0.9357],
         ...,
         [0.6780, 0.2435, 0.8161,  ..., 0.3047, 0.3814, 0.3935],
         [0.8792, 0.5881, 0.0351,  ..., 0.0170, 0.5588, 0.3681],
         [0.9821, 0.2575, 0.5620,  ..., 0.3092, 0.2325, 0.7168]],

        [[0.4192, 0.7355, 0.5604,  ..., 0.7203, 0.0137, 0.9814],
         [0.6458, 0.9577, 0.8969,  ..., 0.7989, 0.9547, 0.6039],
         [0.4072, 0.6792, 0.5506,  ..., 0.9727, 0.2077, 0.

In [21]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 224]), 3)

### Zeros and Ones

In [22]:
#creating all zeros
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [24]:
#creating all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating tensors with a range

In [26]:
one_to_hundred=torch.arange(start=0,end=100,step=9)
one_to_hundred

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [27]:
#creating a tensor like
hundred_zeros=torch.zeros_like(input=one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])