In [24]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cpu


## Intoduction to Tensors


### Creating tensors

In [41]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [42]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [43]:
scalar.ndim


0

In [44]:
#get tensor back as python int
scalar.item()

7

In [45]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [46]:
vector.ndim


1

In [47]:
vector.shape


torch.Size([2])

In [48]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [49]:
MATRIX.ndim


2

In [50]:
MATRIX.shape


torch.Size([2, 2])

In [51]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [52]:
TENSOR.ndim

3

In [53]:
TENSOR.shape

torch.Size([2, 3, 3])

In [54]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
TENSOR[0][0]

tensor([1, 2, 3])

In [56]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [60]:
#creating a random tensors
random_tensor=torch.rand(2,3,3)
random_tensor

tensor([[[0.0937, 0.3030, 0.6819],
         [0.6403, 0.9223, 0.3751],
         [0.5902, 0.3721, 0.4733]],

        [[0.1648, 0.4131, 0.6029],
         [0.4771, 0.0446, 0.6527],
         [0.4122, 0.8250, 0.4627]]])

In [61]:
random_tensor.ndim

3

In [64]:
#creating a random tensor with similar shape to a image tensor
random_image_tensor=torch.rand(size=(3,244,224))#colour channel, height and width 
random_image_tensor

tensor([[[0.2964, 0.5461, 0.2810,  ..., 0.1188, 0.8217, 0.4865],
         [0.3528, 0.9247, 0.1382,  ..., 0.0830, 0.1176, 0.9766],
         [0.9444, 0.4440, 0.6139,  ..., 0.1073, 0.4217, 0.8759],
         ...,
         [0.0711, 0.6257, 0.0624,  ..., 0.4287, 0.4453, 0.1845],
         [0.7180, 0.5840, 0.5005,  ..., 0.3559, 0.4621, 0.6499],
         [0.8412, 0.0115, 0.1728,  ..., 0.4135, 0.3020, 0.7183]],

        [[0.5488, 0.2380, 0.6929,  ..., 0.8368, 0.5576, 0.6019],
         [0.5026, 0.7890, 0.3854,  ..., 0.4902, 0.2113, 0.2015],
         [0.4312, 0.3557, 0.6430,  ..., 0.3588, 0.8787, 0.1931],
         ...,
         [0.8013, 0.5987, 0.3046,  ..., 0.7394, 0.9276, 0.3428],
         [0.2633, 0.8883, 0.0235,  ..., 0.0942, 0.3300, 0.9633],
         [0.1436, 0.5658, 0.2584,  ..., 0.3071, 0.8823, 0.8454]],

        [[0.6421, 0.7376, 0.0669,  ..., 0.0088, 0.7930, 0.1395],
         [0.2044, 0.0509, 0.9433,  ..., 0.4057, 0.8610, 0.2111],
         [0.5353, 0.7546, 0.6681,  ..., 0.3421, 0.3236, 0.

In [67]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 224]), 3)

### Zeros and Ones

In [70]:
#creating all zeros
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [71]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [72]:
#creating all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [73]:
ones.dtype

torch.float32

### Creating tensors with a range

In [81]:
one_to_hundred=torch.arange(start=0,end=100,step=9)
one_to_hundred

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [83]:
#creating a tensor like
hundred_zeros=torch.zeros_like(input=one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])