In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
print(torch.__version__)

2.7.1+cpu


## Intoduction to Tensors

### Creating tensors

In [2]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector=torch.tensor((7,11))
vector

tensor([ 7, 11])

In [7]:
vector.ndim


1

In [8]:
vector.shape


torch.Size([2])

In [9]:
#matrix
MATRIX=torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim


2

In [11]:
MATRIX.shape


torch.Size([2, 2])

In [12]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
TENSOR[0][0]

tensor([1, 2, 3])

In [17]:
TENSOR[0][0][0]

tensor(1)

### Random Tensors

In [18]:
#creating a random tensors
random_tensor=torch.rand(2,3,3)
random_tensor

tensor([[[0.5341, 0.1281, 0.4287],
         [0.4682, 0.8114, 0.1881],
         [0.7664, 0.9262, 0.2085]],

        [[0.3593, 0.8794, 0.4526],
         [0.3659, 0.9897, 0.8812],
         [0.4574, 0.3759, 0.6074]]])

In [19]:
random_tensor.ndim

3

In [20]:
#creating a random tensor with similar shape to a image tensor
random_image_tensor=torch.rand(size=(3,244,224))#colour channel, height and width 
random_image_tensor

tensor([[[0.6011, 0.1524, 0.6820,  ..., 0.9271, 0.5525, 0.6520],
         [0.8790, 0.0620, 0.8490,  ..., 0.5154, 0.8861, 0.5986],
         [0.1645, 0.3614, 0.4636,  ..., 0.0292, 0.4254, 0.5479],
         ...,
         [0.3779, 0.7639, 0.5964,  ..., 0.2630, 0.0366, 0.6310],
         [0.2030, 0.4572, 0.9504,  ..., 0.2197, 0.6620, 0.4625],
         [0.8482, 0.2336, 0.5502,  ..., 0.0504, 0.1605, 0.3668]],

        [[0.3986, 0.8077, 0.0765,  ..., 0.8512, 0.1122, 0.8841],
         [0.6019, 0.4783, 0.5622,  ..., 0.0596, 0.3727, 0.9784],
         [0.4479, 0.7496, 0.4591,  ..., 0.5645, 0.5006, 0.9613],
         ...,
         [0.3749, 0.8400, 0.6630,  ..., 0.3179, 0.2303, 0.7713],
         [0.6557, 0.5400, 0.1026,  ..., 0.7112, 0.0771, 0.4298],
         [0.0082, 0.0791, 0.7100,  ..., 0.0278, 0.5617, 0.3979]],

        [[0.6855, 0.7759, 0.2227,  ..., 0.7382, 0.7283, 0.5741],
         [0.8796, 0.4665, 0.4943,  ..., 0.0131, 0.3495, 0.3140],
         [0.1383, 0.7942, 0.5404,  ..., 0.9932, 0.3366, 0.

In [21]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 224]), 3)

### Zeros and Ones

In [22]:
#creating all zeros
zeros=torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [24]:
#creating all ones
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating tensors with a range

In [26]:
one_to_hundred=torch.arange(start=0,end=100,step=9)
one_to_hundred

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [27]:
#creating a tensor like
hundred_zeros=torch.zeros_like(input=one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [28]:
#lfoat 32
float_32_tensor=torch.tensor([3.0,6.0,9.0], 
                             dtype=None, # specify dtype of tensor, if None, it will be inferred from data
                             device=None, # specify device of tensor, if None, it will be inferred from data
                             requires_grad=False # specify if tensor requires gradient, default is False
                             )
float_32_tensor, float_32_tensor.dtype


(tensor([3., 6., 9.]), torch.float32)

In [29]:
floar_16_tensor=float_32_tensor.type(torch.float16)
floar_16_tensor, floar_16_tensor.dtype


(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [30]:
float_32_tensor*floar_16_tensor,(float_32_tensor*floar_16_tensor).dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [31]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([3, 6, 9], dtype=torch.int32), torch.int32)

In [32]:
int_32_tensor*floar_16_tensor,(int_32_tensor*floar_16_tensor).dtype

(tensor([ 9., 36., 81.], dtype=torch.float16), torch.float16)

### Getting info from Tensors
info like: datatype, shape of tensor and device its present

In [33]:
#creating a general tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.9180, 0.7168, 0.1688, 0.6830],
        [0.9528, 0.8959, 0.4347, 0.8527],
        [0.5125, 0.2681, 0.4367, 0.6388]])

In [34]:
print('Datatype of Tensor: ',some_tensor.dtype)
print('Shape of Tensor: ',some_tensor.shape)
print('Device of Tensor: ',some_tensor.device)

Datatype of Tensor:  torch.float32
Shape of Tensor:  torch.Size([3, 4])
Device of Tensor:  cpu


### Manipulating a tensor

In [35]:
#creating a dummy tensor
dummy_tensor=torch.tensor([1,2,3])
dummy_tensor+100

tensor([101, 102, 103])

In [36]:
dummy_tensor*100

tensor([100, 200, 300])

In [37]:
dummy_tensor-100

tensor([-99, -98, -97])

In [38]:
torch.mul(dummy_tensor,10)

tensor([10, 20, 30])

In [39]:
torch.add(dummy_tensor,10)

tensor([11, 12, 13])

### Matrix mulltiplication

In [40]:
test_tensor=torch.tensor([1,2,3])
second_tensor=torch.tensor([10,20,30])
test_tensor, second_tensor

(tensor([1, 2, 3]), tensor([10, 20, 30]))

In [41]:
%%time
test_tensor*second_tensor

CPU times: total: 0 ns
Wall time: 141 μs


tensor([10, 40, 90])

In [42]:
%%time
torch.matmul(test_tensor,second_tensor)

CPU times: total: 0 ns
Wall time: 428 μs


tensor(140)

In [43]:
#matrix multiplication by hand
1*10+2*20+3*30

140

In [44]:
%%time
val=0
for i in range(len(test_tensor)):
    val+=test_tensor[i]*second_tensor[i]
print(val)

tensor(140)
CPU times: total: 0 ns
Wall time: 1.36 ms


### Finding min, max, mean ,sum , etc (tensor aggregation)

In [45]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [46]:
torch.min(x),torch.max(x),torch.sum(x)

(tensor(0), tensor(90), tensor(450))

In [47]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean() # mean requires float tensor

(tensor(45.), tensor(45.))

In [48]:
#finding positional max and min
x.argmax(),x.argmin()

(tensor(9), tensor(0))

### Reshaping, Stacking, Sqeezing and Unsqueeezing tensors

In [82]:
x=torch.arange(1.,10.)
x,x.dtype,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32, torch.Size([9]))

In [83]:
x_reshaped=x.reshape(1,3,3)
x_reshaped,x_reshaped.dtype,x_reshaped.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32,
 torch.Size([1, 3, 3]))

In [84]:
z=x.view(3,3)
z,z.dtype,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.float32,
 torch.Size([3, 3]))

In [85]:
print(f"original x: {x}, z: {z}")
z[:,0]=9
print(f"After changeing z x: {x}, z: {z}")

original x: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), z: tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
After changeing z x: tensor([9., 2., 3., 9., 5., 6., 9., 8., 9.]), z: tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]])


In [86]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked,x_stacked.dtype,x_stacked.shape

(tensor([[9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.],
         [9., 2., 3., 9., 5., 6., 9., 8., 9.]]),
 torch.float32,
 torch.Size([4, 9]))

In [87]:
print(x_reshaped,x_reshaped.dtype,x_reshaped.shape)
x_squeezed=x_reshaped.squeeze()
print(x_squeezed,x_squeezed.dtype,x_squeezed.shape)

tensor([[[9., 2., 3.],
         [9., 5., 6.],
         [9., 8., 9.]]]) torch.float32 torch.Size([1, 3, 3])
tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]]) torch.float32 torch.Size([3, 3])


In [91]:
print(x_squeezed,x_squeezed.dtype,x_squeezed.shape)
x_unsqueezed=x_squeezed.unsqueeze(dim=2)
print(x_unsqueezed,x_unsqueezed.dtype,x_unsqueezed.shape)

tensor([[9., 2., 3.],
        [9., 5., 6.],
        [9., 8., 9.]]) torch.float32 torch.Size([3, 3])
tensor([[[9.],
         [2.],
         [3.]],

        [[9.],
         [5.],
         [6.]],

        [[9.],
         [8.],
         [9.]]]) torch.float32 torch.Size([3, 3, 1])


## Indexing (Selecting data from tensors)

In [92]:
x=torch.arange(1.,10.).reshape(1,3,3)
x,x.dtype,x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.float32,
 torch.Size([1, 3, 3]))

In [93]:
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [94]:
x[0][0]

tensor([1., 2., 3.])

In [95]:
x[0][0][0]

tensor(1.)

In [97]:
x[:,0]

tensor([[1., 2., 3.]])

In [98]:
x[:,:,0]

tensor([[1., 4., 7.]])

In [100]:
x[0,1,:]

tensor([4., 5., 6.])

## Reproducbility(trying to kake random out of random)

In [110]:
import torch

rand_tensor_a=torch.rand(3,4)
rand_tensor_b=torch.rand(3,4)

print(rand_tensor_a, rand_tensor_b,rand_tensor_a==rand_tensor_b)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]]) tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090]]) tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [111]:
import torch

RANDOM_SEED=42

torch.manual_seed(RANDOM_SEED)  # Set seed for reproducibility

rand_tensor_c=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)  # Set seed for reproducibility

rand_tensor_d=torch.rand(3,4)

print(rand_tensor_c, rand_tensor_d,rand_tensor_c==rand_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
